# Generated by Django 5.1.1 on 2024-09-21 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram_feed.instagramaccount')),
            ],
        ),
    ]
