# Generated by Django 5.1.1 on 2024-09-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_feed', '0002_remove_instagramaccount_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='instagram_images/'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='instagram_videos/'),
        ),
    ]
