# Generated by Django 5.1.1 on 2024-09-23 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_feed', '0003_alter_instagrampost_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='InstagramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='instagram_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='instagram_feed.instagrampost')),
            ],
        ),
    ]
