# Generated by Django 5.1.1 on 2024-09-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_feed', '0004_remove_instagrampost_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='video_url',
        ),
    ]
