# Generated by Django 5.1.1 on 2024-09-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_feed', '0005_remove_instagrampost_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('media_url', models.FileField(upload_to='instagram_media/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='instagram_feed.instagrampost')),
            ],
        ),
        migrations.DeleteModel(
            name='InstagramImage',
        ),
    ]
