# Generated by Django 5.1.1 on 2024-09-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_feed', '0006_instagrammedia_delete_instagramimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='post_id',
            field=models.CharField(max_length=50),
        ),
    ]
