# Generated by Django 5.1.1 on 2024-09-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_feed', '0007_alter_instagrampost_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
